{{ config(
    materialized='table',
    meta = {
        'dagster': {
            'group': 'prep',
            'domain': 'entetcli',
            'layer': 'prep'
        },
        'description': 'Entêtes clients'
    },
) }}

    /*
    ============================================================================
    PREP MODEL : entetcli
    ============================================================================
    Generated : 2025-12-29 11:37:37
    Source    : ods.entetcli
Description : Entêtes clients
    Rows ODS  : 15,092
    Cols ODS  : 463
    Cols PREP : 210 (+ _prep_loaded_at)
    Strategy  : TABLE
    ============================================================================
    */

    SELECT
        "cod_cli" AS cod_cli,
    "typ_sai" AS typ_sai,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "achev" AS achev,
    "typ_cde" AS typ_cde,
    "dat_cde" AS dat_cde,
    "dat_px" AS dat_px,
    "qui" AS qui,
    "ref_cde" AS ref_cde,
    "not_ref" AS not_ref,
    "dat_liv" AS dat_liv,
    "dat_livd" AS dat_livd,
    "dat_dep" AS dat_dep,
    "depot" AS depot,
    "civ_fac" AS civ_fac,
    "adr_fac_1" AS adr_fac_1,
    "adr_fac_2" AS adr_fac_2,
    "adr_fac_3" AS adr_fac_3,
    "k_postf" AS k_postf,
    "villef" AS villef,
    "paysf" AS paysf,
    "chif_bl" AS chif_bl,
    "fra_app" AS fra_app,
    "proforma" AS proforma,
    "liasse" AS liasse,
    "num_tel" AS num_tel,
    "num_fax" AS num_fax,
    "civ_liv" AS civ_liv,
    "adr_liv_1" AS adr_liv_1,
    "adr_liv_2" AS adr_liv_2,
    "adr_liv_3" AS adr_liv_3,
    "k_postl" AS k_postl,
    "villel" AS villel,
    "paysl" AS paysl,
    "devise" AS devise,
    "tx_ech_d" AS tx_ech_d,
    "iden_ce" AS iden_ce,
    "code_reg" AS code_reg,
    "code_ech" AS code_ech,
    "nb_ech" AS nb_ech,
    "langue" AS langue,
    "regime" AS regime,
    "type_fac" AS type_fac,
    "fac_dvs" AS fac_dvs,
    "fac_pxa" AS fac_pxa,
    "div_fac_1" AS div_fac_1,
    "div_fac_2" AS div_fac_2,
    "val_fac_1" AS val_fac_1,
    "edt_arc" AS edt_arc,
    "cl_grp" AS cl_grp,
    "cl_fact" AS cl_fact,
    "cl_paye" AS cl_paye,
    "tarif" AS tarif,
    "region" AS region,
    "famille" AS famille,
    "cat_tar" AS cat_tar,
    "commerc_1" AS commerc_1,
    "commerc_2" AS commerc_2,
    "no_tarif" AS no_tarif,
    "borne" AS borne,
    "relk_bp" AS relk_bp,
    "der_bp" AS der_bp,
    "nb_bp" AS nb_bp,
    "mnt_rlk" AS mnt_rlk,
    "bl_sai" AS bl_sai,
    "mt_port" AS mt_port,
    "poids" AS poids,
    "mod_liv" AS mod_liv,
    "colis" AS colis,
    "zon_geo" AS zon_geo,
    "transpor" AS transpor,
    "mt_cde" AS mt_cde,
    "no_fact" AS no_fact,
    "fac_edi" AS fac_edi,
    "fac_maj" AS fac_maj,
    "dat_fac" AS dat_fac,
    "mt_reg" AS mt_reg,
    "mt_acom" AS mt_acom,
    "zal_1" AS zal_1,
    "zal_3" AS zal_3,
    "zal_4" AS zal_4,
    "zal_5" AS zal_5,
    "znu_1" AS znu_1,
    "znu_2" AS znu_2,
    "znu_3" AS znu_3,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zta_5" AS zta_5,
    "zda_5" AS zda_5,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "edt_bp" AS edt_bp,
    "edt_bl" AS edt_bl,
    "edt_fac" AS edt_fac,
    "maj_ach" AS maj_ach,
    "blocage" AS blocage,
    "ori_cde" AS ori_cde,
    "qui_liv" AS qui_liv,
    "palette" AS palette,
    "informat" AS informat,
    "mt_rport" AS mt_rport,
    "cod_dev" AS cod_dev,
    "typ_con" AS typ_con,
    "dat_dev" AS dat_dev,
    "no_cheque" AS no_cheque,
    "no_cb" AS no_cb,
    "no_devis" AS no_devis,
    "mt_fact" AS mt_fact,
    "no_caisse" AS no_caisse,
    "comment" AS comment,
    "mt_ht" AS mt_ht,
    "hr_sai" AS hr_sai,
    "dat_ech" AS dat_ech,
    "bl_ori" AS bl_ori,
    "edi_rlv" AS edi_rlv,
    "motif_av" AS motif_av,
    "mt_ht_dev" AS mt_ht_dev,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "zlo_3" AS zlo_3,
    "zlo_5" AS zlo_5,
    "k_post2f" AS k_post2f,
    "k_post2l" AS k_post2l,
    "qui_exp" AS qui_exp,
    "volume" AS volume,
    "no_info" AS no_info,
    "sta_pce" AS sta_pce,
    "semaine" AS semaine,
    "dat_mad" AS dat_mad,
    "no_lance" AS no_lance,
    "ind_bp" AS ind_bp,
    "qui_dbl" AS qui_dbl,
    "mt_fach" AS mt_fach,
    "bp_ini" AS bp_ini,
    "mt_ini" AS mt_ini,
    "inc_deb" AS inc_deb,
    "trs_deb" AS trs_deb,
    "com_liv_1" AS com_liv_1,
    "adrfac4" AS adrfac4,
    "adrliv4" AS adrliv4,
    "cod_tlv" AS cod_tlv,
    "hr_bp" AS hr_bp,
    "dat_bp" AS dat_bp,
    "no_bpr" AS no_bpr,
    "dat_va" AS dat_va,
    "pce_a" AS pce_a,
    "ndos" AS ndos,
    "dat_rep" AS dat_rep,
    "cpt_bq" AS cpt_bq,
    "no_ordre" AS no_ordre,
    "no_camion" AS no_camion,
    "dat_rec" AS dat_rec,
    "hr_bl" AS hr_bl,
    "dat_bl" AS dat_bl,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "retr_cess" AS retr_cess,
    "liv_cpl" AS liv_cpl,
    "temps" AS temps,
    "arc_mail" AS arc_mail,
    "civ_cde" AS civ_cde,
    "adr_cde_1" AS adr_cde_1,
    "adr_cde_2" AS adr_cde_2,
    "adr_cde_3" AS adr_cde_3,
    "adr_cde_4" AS adr_cde_4,
    "villec" AS villec,
    "paysc" AS paysc,
    "k_post2c" AS k_post2c,
    "no_tar_loc" AS no_tar_loc,
    "no_carte" AS no_carte,
    "typ_elem" AS typ_elem,
    "cat_cum" AS cat_cum,
    "tar_fil_1" AS tar_fil_1,
    "tar_cum_1" AS tar_cum_1,
    "no_pre_fact" AS no_pre_fact,
    "dat_vald" AS dat_vald,
    "cod_for" AS cod_for,
    "cde_ini" AS cde_ini,
    "prix_franco" AS prix_franco,
    "poi_ini" AS poi_ini,
    "cod_site" AS cod_site,
    "s2_famille" AS s2_famille,
    "no_port" AS no_port,
    "no_ordre_m" AS no_ordre_m,
    "uniq_id" AS uniq_id,
    "metre_lin" AS metre_lin,
    "lias_bl" AS lias_bl,
    "cod_op" AS cod_op,
    "prc_aco" AS prc_aco,
    "mt_aco_ori" AS mt_aco_ori,
    "lien_aco" AS lien_aco,
    "pal_sol" AS pal_sol,
    "corresp_1" AS corresp_1,
    "mt_reg_dev" AS mt_reg_dev,
    "num_tel_cde" AS num_tel_cde,
    "num_fax_cde" AS num_fax_cde,
    "num_tel_liv" AS num_tel_liv,
    "num_fax_liv" AS num_fax_liv,
    "edt_cde" AS edt_cde,
    "edt_dev" AS edt_dev,
    "mt_titresto" AS mt_titresto,
    "_etl_loaded_at" AS _etl_loaded_at,
    "_etl_run_id" AS _etl_run_id,
    "_etl_valid_from" AS _etl_source_timestamp,
    CURRENT_TIMESTAMP AS _prep_loaded_at
    FROM {{ source('ods', 'entetcli') }}
    