{{ config(
    materialized='incremental',
    meta = {
        'dagster': {
            'group': 'prep',
            'domain': 'histolig',
            'layer': 'prep'
        },
        'description': 'Historique lignes mouvements'
    },
    unique_key='uniq_id',
    incremental_strategy='merge',
    on_schema_change='sync_all_columns',
    post_hook=[
        "{% if is_incremental() %}DELETE FROM {{ this }} t WHERE NOT EXISTS (SELECT 1 FROM {{ source('ods', 'histolig') }} s WHERE s.uniq_id = t.uniq_id){% endif %}",
        "CREATE UNIQUE INDEX IF NOT EXISTS histolig_pkey ON {{ this }} USING btree (uniq_id)",
        "CREATE INDEX IF NOT EXISTS idx_histolig_etl_source_timestamp ON {{ this }} USING btree (_etl_source_timestamp)",
        "ANALYZE {{ this }}"
    ]
) }}

    /*
    ============================================================================
    PREP MODEL : histolig
    ============================================================================
    Generated : 2025-12-29 11:38:39
    Source    : ods.histolig
Description : Historique lignes mouvements
    Rows ODS  : 1,913,483
    Cols ODS  : 442
    Cols PREP : 213 (+ _prep_loaded_at)
    Strategy  : INCREMENTAL
    ============================================================================
    */

    SELECT
        "cod_pro" AS cod_pro,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "depot" AS depot,
    "dat_mvt" AS dat_mvt,
    "typ_mvt" AS typ_mvt,
    "ref_mvt" AS ref_mvt,
    "es_mvt" AS es_mvt,
    "qte_unit" AS qte_unit,
    "px_unit" AS px_unit,
    "sous_type" AS sous_type,
    "typ_elem" AS typ_elem,
    "cod_cf" AS cod_cf,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "div_fac" AS div_fac,
    "no_ligne" AS no_ligne,
    "nom_pro" AS nom_pro,
    "qte" AS qte,
    "px_vte" AS px_vte,
    "remise1" AS remise1,
    "remise2" AS remise2,
    "rem_app" AS rem_app,
    "refint" AS refint,
    "groupe" AS groupe,
    "famille" AS famille,
    "s_famille" AS s_famille,
    "fam_cpt" AS fam_cpt,
    "uni_vte" AS uni_vte,
    "lib_univ" AS lib_univ,
    "lib_conv" AS lib_conv,
    "conv_px" AS conv_px,
    "cod_fou" AS cod_fou,
    "refext" AS refext,
    "devise" AS devise,
    "px_ach" AS px_ach,
    "uni_ach" AS uni_ach,
    "lib_unia" AS lib_unia,
    "lib_cona" AS lib_cona,
    "fam_tar" AS fam_tar,
    "code_tva" AS code_tva,
    "enc_db" AS enc_db,
    "calcul" AS calcul,
    "px_refv" AS px_refv,
    "px_refa" AS px_refa,
    "px_ach_d" AS px_ach_d,
    "pmp" AS pmp,
    "zal_1" AS zal_1,
    "znu_3" AS znu_3,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_2" AS zta_2,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zda_2" AS zda_2,
    "zda_5" AS zda_5,
    "gratuit" AS gratuit,
    "forcer" AS forcer,
    "dat_liv" AS dat_liv,
    "commerc_1" AS commerc_1,
    "commerc_2" AS commerc_2,
    "total" AS total,
    "tot_txt" AS tot_txt,
    "typ_pha" AS typ_pha,
    "conv_sto" AS conv_sto,
    "px_vte_i" AS px_vte_i,
    "dev_vte" AS dev_vte,
    "lien_nmc" AS lien_nmc,
    "maj_stk" AS maj_stk,
    "edt_nmc" AS edt_nmc,
    "conv_md" AS conv_md,
    "qte_cde" AS qte_cde,
    "n_surlig" AS n_surlig,
    "longueur" AS longueur,
    "calc_uv" AS calc_uv,
    "qte_uc" AS qte_uc,
    "cal_marg" AS cal_marg,
    "px_rvt" AS px_rvt,
    "coef_dep" AS coef_dep,
    "remise3" AS remise3,
    "poid_tot" AS poid_tot,
    "maj_stat" AS maj_stat,
    "sf_tar" AS sf_tar,
    "qui" AS qui,
    "mt_ht" AS mt_ht,
    "lien_con" AS lien_con,
    "master" AS master,
    "ord_nmc" AS ord_nmc,
    "cod_ori" AS cod_ori,
    "dat_ret" AS dat_ret,
    "garantie" AS garantie,
    "cde_cf" AS cde_cf,
    "lig_fou" AS lig_fou,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "zlo_3" AS zlo_3,
    "zlo_5" AS zlo_5,
    "typ_rem_3" AS typ_rem_3,
    "qte_rlf" AS qte_rlf,
    "mt_rlf" AS mt_rlf,
    "volume" AS volume,
    "zon_lib_1" AS zon_lib_1,
    "num_ave" AS num_ave,
    "tx_com" AS tx_com,
    "no_of" AS no_of,
    "no_reafab" AS no_reafab,
    "no_reacons" AS no_reacons,
    "no_lance" AS no_lance,
    "dafaca" AS dafaca,
    "dat_mad" AS dat_mad,
    "no_bl_a" AS no_bl_a,
    "no_info" AS no_info,
    "no_serie" AS no_serie,
    "lien_emp" AS lien_emp,
    "reg_deb" AS reg_deb,
    "no_contrat" AS no_contrat,
    "type_prix" AS type_prix,
    "hr_vp" AS hr_vp,
    "dat_vp" AS dat_vp,
    "qui_p" AS qui_p,
    "ind_con" AS ind_con,
    "lig_con" AS lig_con,
    "cod_conv" AS cod_conv,
    "ndos" AS ndos,
    "s3_tar" AS s3_tar,
    "s4_tar" AS s4_tar,
    "reg_fact" AS reg_fact,
    "crit_cli_df" AS crit_cli_df,
    "typ_gra" AS typ_gra,
    "nb_ua" AS nb_ua,
    "nb_uv" AS nb_uv,
    "pp_ua" AS pp_ua,
    "pp_uv" AS pp_uv,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "lien_frais" AS lien_frais,
    "dat_cc" AS dat_cc,
    "poid_net" AS poid_net,
    "s3_famille" AS s3_famille,
    "s4_famille" AS s4_famille,
    "list_crit" AS list_crit,
    "qui_v" AS qui_v,
    "num_lot" AS num_lot,
    "num_colis" AS num_colis,
    "no_mvtbois" AS no_mvtbois,
    "no_mvtobois" AS no_mvtobois,
    "no_opebois" AS no_opebois,
    "nom_pr2" AS nom_pr2,
    "no_lot" AS no_lot,
    "mt_ttc" AS mt_ttc,
    "px_rvt_bo" AS px_rvt_bo,
    "no_unique" AS no_unique,
    "mt_trsc" AS mt_trsc,
    "num_prix" AS num_prix,
    "no_ligct" AS no_ligct,
    "no_grp_c" AS no_grp_c,
    "no_ctbois" AS no_ctbois,
    "no_ordre" AS no_ordre,
    "px_franco" AS px_franco,
    "px_std" AS px_std,
    "ach_ctr" AS ach_ctr,
    "px_ree" AS px_ree,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "px_trs" AS px_trs,
    "consigne" AS consigne,
    "det_frais" AS det_frais,
    "gen_csg" AS gen_csg,
    "hr_mod" AS hr_mod,
    "no_tarif" AS no_tarif,
    "hr_crt" AS hr_crt,
    "no_batch" AS no_batch,
    "uniq_id" AS uniq_id,
    "no_devis" AS no_devis,
    "mt_pa" AS mt_pa,
    "mt_pr" AS mt_pr,
    "mt_pm" AS mt_pm,
    "nb_uv1" AS nb_uv1,
    "cod_op" AS cod_op,
    "MScod_fou" AS mscod_fou,
    "MScde_fou" AS mscde_fou,
    "MSlig_fou" AS mslig_fou,
    "pays_ori" AS pays_ori,
    "no_u_perte" AS no_u_perte,
    "px_deb" AS px_deb,
    "hr_mvt" AS hr_mvt,
    "qte_por" AS qte_por,
    "mt_frais" AS mt_frais,
    "px_rvt_vte" AS px_rvt_vte,
    "cod_fou_df" AS cod_fou_df,
    "cod_prolie" AS cod_prolie,
    "cod_rvt_ach" AS cod_rvt_ach,
    "cod_rvt_vte" AS cod_rvt_vte,
    "px_up" AS px_up,
    "qte_up" AS qte_up,
    "qte_ro" AS qte_ro,
    "qte_rc" AS qte_rc,
    "qte_rb" AS qte_rb,
    "marque" AS marque,
    "tare_p_2" AS tare_p_2,
    "no_deb" AS no_deb,
    "lig_deb" AS lig_deb,
    "cond_rem_2" AS cond_rem_2,
    "cod_nom" AS cod_nom,
    "mt_titresto" AS mt_titresto,
    "_etl_valid_from" AS _etl_source_timestamp,
    "_etl_run_id" AS _etl_run_id,
    CURRENT_TIMESTAMP AS _prep_loaded_at
    FROM {{ source('ods', 'histolig') }}
{% if is_incremental() %}
WHERE "_etl_valid_from" > (
    SELECT COALESCE(MAX(_etl_source_timestamp), '1900-01-01'::timestamp)
    FROM {{ this }}
)
{% endif %}
    