{{ config(
    materialized='incremental',
    meta = {
        'dagster': {
            'group': 'prep',
            'domain': 'histoent',
            'layer': 'prep'
        },
        'description': 'Historique entêtes'
    },
    unique_key='uniq_id',
    incremental_strategy='merge',
    on_schema_change='sync_all_columns',
    post_hook=[
        "CREATE INDEX IF NOT EXISTS idx_histoent_current ON {{ this }} USING btree (_etl_is_current) WHERE (_etl_is_current = true)",
        "CREATE INDEX IF NOT EXISTS idx_histoent_pk_current ON {{ this }} USING btree (uniq_id, _etl_is_current)",
        "ANALYZE {{ this }}"
    ]
) }}

    /*
    ============================================================================
    PREP MODEL : histoent
    ============================================================================
    Generated : 2025-12-31 12:04:35
    Source    : ods.histoent
Description : Historique entêtes
    Rows ODS  : 5,163
    Cols ODS  : 453
    Cols PREP : 210 (+ _prep_loaded_at)
    Strategy  : INCREMENTAL
    ============================================================================
    */

    SELECT
        "typ_mvt" AS typ_mvt,
    "cod_cf" AS cod_cf,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "typ_cde" AS typ_cde,
    "dat_cde" AS dat_cde,
    "dat_px" AS dat_px,
    "qui" AS qui,
    "ref_cde" AS ref_cde,
    "not_ref" AS not_ref,
    "dat_liv" AS dat_liv,
    "dat_livd" AS dat_livd,
    "dat_dep" AS dat_dep,
    "depot" AS depot,
    "civ_fac" AS civ_fac,
    "adr_fac_1" AS adr_fac_1,
    "adr_fac_2" AS adr_fac_2,
    "adr_fac_3" AS adr_fac_3,
    "villef" AS villef,
    "paysf" AS paysf,
    "chif_bl" AS chif_bl,
    "liasse" AS liasse,
    "num_tel" AS num_tel,
    "num_fax" AS num_fax,
    "civ_liv" AS civ_liv,
    "adr_liv_1" AS adr_liv_1,
    "adr_liv_2" AS adr_liv_2,
    "adr_liv_3" AS adr_liv_3,
    "k_postl" AS k_postl,
    "villel" AS villel,
    "paysl" AS paysl,
    "devise" AS devise,
    "tx_ech_d" AS tx_ech_d,
    "iden_ce" AS iden_ce,
    "code_reg" AS code_reg,
    "code_ech" AS code_ech,
    "langue" AS langue,
    "regime" AS regime,
    "type_fac" AS type_fac,
    "fac_dvs" AS fac_dvs,
    "fac_ttc" AS fac_ttc,
    "fac_pxa" AS fac_pxa,
    "cl_grp" AS cl_grp,
    "cl_fact" AS cl_fact,
    "cl_paye" AS cl_paye,
    "region" AS region,
    "famille" AS famille,
    "cat_tar" AS cat_tar,
    "commerc_1" AS commerc_1,
    "commerc_2" AS commerc_2,
    "no_tarif" AS no_tarif,
    "mt_port" AS mt_port,
    "mod_liv" AS mod_liv,
    "colis" AS colis,
    "zon_geo" AS zon_geo,
    "transpor" AS transpor,
    "mt_cde" AS mt_cde,
    "no_fact" AS no_fact,
    "dat_fac" AS dat_fac,
    "mt_reg" AS mt_reg,
    "mt_acom" AS mt_acom,
    "zal_1" AS zal_1,
    "zal_2" AS zal_2,
    "zal_3" AS zal_3,
    "zal_5" AS zal_5,
    "znu_1" AS znu_1,
    "znu_2" AS znu_2,
    "znu_3" AS znu_3,
    "znu_4" AS znu_4,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_2" AS zta_2,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zta_5" AS zta_5,
    "zda_1" AS zda_1,
    "zda_5" AS zda_5,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "edt_bl" AS edt_bl,
    "edt_fac" AS edt_fac,
    "maj_ach" AS maj_ach,
    "qui_liv" AS qui_liv,
    "ori_cde" AS ori_cde,
    "palette" AS palette,
    "mt_rport" AS mt_rport,
    "cod_fof_1" AS cod_fof_1,
    "cod_fof_2" AS cod_fof_2,
    "cod_fof_3" AS cod_fof_3,
    "cod_fof_4" AS cod_fof_4,
    "cod_fof_5" AS cod_fof_5,
    "cod_fof_6" AS cod_fof_6,
    "no_cheque" AS no_cheque,
    "no_cb" AS no_cb,
    "no_devis" AS no_devis,
    "no_caisse" AS no_caisse,
    "dev_reg" AS dev_reg,
    "hr_sai" AS hr_sai,
    "mt_ht" AS mt_ht,
    "dat_ech" AS dat_ech,
    "bl_ori" AS bl_ori,
    "mt_fact" AS mt_fact,
    "transit" AS transit,
    "motif_av" AS motif_av,
    "mt_ht_dev" AS mt_ht_dev,
    "no_bl_a" AS no_bl_a,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "zlo_3" AS zlo_3,
    "zlo_5" AS zlo_5,
    "k_post2f" AS k_post2f,
    "k_post2l" AS k_post2l,
    "qui_exp" AS qui_exp,
    "volume" AS volume,
    "no_info" AS no_info,
    "no_fa_a_1" AS no_fa_a_1,
    "no_fa_a_2" AS no_fa_a_2,
    "no_fa_a_3" AS no_fa_a_3,
    "no_fa_a_4" AS no_fa_a_4,
    "no_lance" AS no_lance,
    "poids" AS poids,
    "cod_prof_1" AS cod_prof_1,
    "cod_prof_2" AS cod_prof_2,
    "cod_prof_3" AS cod_prof_3,
    "cod_prof_4" AS cod_prof_4,
    "cod_prof_5" AS cod_prof_5,
    "cod_prof_6" AS cod_prof_6,
    "mt_fach" AS mt_fach,
    "bp_ini" AS bp_ini,
    "inc_deb" AS inc_deb,
    "trs_deb" AS trs_deb,
    "adrfac4" AS adrfac4,
    "adrliv4" AS adrliv4,
    "cod_tlv" AS cod_tlv,
    "hr_bp" AS hr_bp,
    "dat_bp" AS dat_bp,
    "ndos" AS ndos,
    "dat_rep" AS dat_rep,
    "cpt_bq" AS cpt_bq,
    "dat_rec" AS dat_rec,
    "hr_bl" AS hr_bl,
    "dat_bl" AS dat_bl,
    "edi_rlv" AS edi_rlv,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "retr_cess" AS retr_cess,
    "typ_con" AS typ_con,
    "dat_enl" AS dat_enl,
    "civ_cde" AS civ_cde,
    "adr_cde_1" AS adr_cde_1,
    "adr_cde_2" AS adr_cde_2,
    "adr_cde_3" AS adr_cde_3,
    "adr_cde_4" AS adr_cde_4,
    "villec" AS villec,
    "paysc" AS paysc,
    "k_post2c" AS k_post2c,
    "no_tar_loc" AS no_tar_loc,
    "no_carte" AS no_carte,
    "typ_elem" AS typ_elem,
    "usr_not" AS usr_not,
    "cat_cum" AS cat_cum,
    "tar_fil_1" AS tar_fil_1,
    "tar_cum_1" AS tar_cum_1,
    "cod_for" AS cod_for,
    "cde_ini" AS cde_ini,
    "pays_e" AS pays_e,
    "typ_fac_edi" AS typ_fac_edi,
    "prix_franco" AS prix_franco,
    "cod_site" AS cod_site,
    "no_ctrl_qua" AS no_ctrl_qua,
    "memory_decimal_1" AS memory_decimal_1,
    "memory_decimal_2" AS memory_decimal_2,
    "memory_decimal_5" AS memory_decimal_5,
    "s2_famille" AS s2_famille,
    "no_ordre_m" AS no_ordre_m,
    "uniq_id" AS uniq_id,
    "hr_mod" AS hr_mod,
    "dat_mad" AS dat_mad,
    "com_liv_1" AS com_liv_1,
    "com_liv_2" AS com_liv_2,
    "comment" AS comment,
    "metre_lin" AS metre_lin,
    "lias_bl" AS lias_bl,
    "cod_op" AS cod_op,
    "mt_aco_ori" AS mt_aco_ori,
    "st_interne" AS st_interne,
    "acq_intra" AS acq_intra,
    "pal_sol" AS pal_sol,
    "bon_pay" AS bon_pay,
    "dat_sai" AS dat_sai,
    "corresp_1" AS corresp_1,
    "num_tel_cde" AS num_tel_cde,
    "num_fax_cde" AS num_fax_cde,
    "num_tel_liv" AS num_tel_liv,
    "num_fax_liv" AS num_fax_liv,
    "edt_cde" AS edt_cde,
    "edt_dev" AS edt_dev,
    "usr_mpce" AS usr_mpce,
    "dat_mpce" AS dat_mpce,
    "usr_his" AS usr_his,
    "dat_his" AS dat_his,
    "hr_his" AS hr_his,
    "cod_fop" AS cod_fop,
    "mt_titresto" AS mt_titresto,
    "_etl_valid_from" AS _etl_source_timestamp,
    "_etl_is_current" AS _etl_is_current,
    "_etl_run_id" AS _etl_run_id,
    CURRENT_TIMESTAMP AS _prep_loaded_at
    FROM {{ source('ods', 'histoent') }}
    WHERE "_etl_is_current" = TRUE
    {% if is_incremental() %}
    AND "_etl_valid_from" > (
        SELECT COALESCE(MAX(_etl_source_timestamp), '1900-01-01'::timestamp)
        FROM {{ this }}
    )
    {% endif %}
    