{{ config(
    materialized='incremental',
    meta = {
        'dagster': {
            'group': 'prep',
            'domain': 'lignecli',
            'layer': 'prep'
        },
    },
    unique_key='uniq_id',
    incremental_strategy='merge',
    on_schema_change='sync_all_columns',
    post_hook=[
        "CREATE INDEX IF NOT EXISTS idx_lignecli_current ON {{ this }} USING btree (_etl_is_current) WHERE (_etl_is_current = true)",
        "CREATE INDEX IF NOT EXISTS idx_lignecli_pk_current ON {{ this }} USING btree (uniq_id, _etl_is_current)",
        "ANALYZE {{ this }}"
    ]
) }}

    /*
    ============================================================================
    PREP MODEL : lignecli
    ============================================================================
    Generated : 2025-12-31 12:04:56
    Source    : ods.lignecli
    Rows ODS  : 51,862
    Cols ODS  : 417
    Cols PREP : 179 (+ _prep_loaded_at)
    Strategy  : INCREMENTAL
    ============================================================================
    */

    SELECT
        "cod_cli" AS cod_cli,
    "typ_sai" AS typ_sai,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "div_fac" AS div_fac,
    "no_ligne" AS no_ligne,
    "sous_type" AS sous_type,
    "typ_elem" AS typ_elem,
    "cod_pro" AS cod_pro,
    "nom_pro" AS nom_pro,
    "qte" AS qte,
    "qte_rlk" AS qte_rlk,
    "qte_dejl" AS qte_dejl,
    "px_vte" AS px_vte,
    "remise1" AS remise1,
    "rem_app" AS rem_app,
    "refint" AS refint,
    "groupe" AS groupe,
    "famille" AS famille,
    "s_famille" AS s_famille,
    "fam_cpt" AS fam_cpt,
    "uni_vte" AS uni_vte,
    "lib_univ" AS lib_univ,
    "lib_conv" AS lib_conv,
    "conv_px" AS conv_px,
    "cod_fou" AS cod_fou,
    "refext" AS refext,
    "devise" AS devise,
    "px_ach" AS px_ach,
    "fam_tar" AS fam_tar,
    "poid_bru" AS poid_bru,
    "code_tva" AS code_tva,
    "enc_db" AS enc_db,
    "calcul" AS calcul,
    "ordre" AS ordre,
    "reg_fact" AS reg_fact,
    "px_refv" AS px_refv,
    "px_refa" AS px_refa,
    "px_ach_d" AS px_ach_d,
    "pmp" AS pmp,
    "cde_fou" AS cde_fou,
    "zal_1" AS zal_1,
    "zal_2" AS zal_2,
    "zal_3" AS zal_3,
    "znu_3" AS znu_3,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_2" AS zta_2,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zda_2" AS zda_2,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "gratuit" AS gratuit,
    "forcer" AS forcer,
    "depot" AS depot,
    "dat_liv" AS dat_liv,
    "dat_livd" AS dat_livd,
    "commerc_1" AS commerc_1,
    "commerc_2" AS commerc_2,
    "tot_txt" AS tot_txt,
    "reliquat" AS reliquat,
    "dev_vte" AS dev_vte,
    "qte_res" AS qte_res,
    "consigne" AS consigne,
    "lien_nmc" AS lien_nmc,
    "maj_stk" AS maj_stk,
    "edt_nmc" AS edt_nmc,
    "no_bp" AS no_bp,
    "n_surlig" AS n_surlig,
    "heure" AS heure,
    "cod_dev" AS cod_dev,
    "cod_opt" AS cod_opt,
    "cod_var" AS cod_var,
    "decl_fou" AS decl_fou,
    "mt_fact" AS mt_fact,
    "maj_stat" AS maj_stat,
    "px_rvt" AS px_rvt,
    "sf_tar" AS sf_tar,
    "mt_ht" AS mt_ht,
    "lien_con" AS lien_con,
    "ord_nmc" AS ord_nmc,
    "cod_ori" AS cod_ori,
    "garantie" AS garantie,
    "lig_fou" AS lig_fou,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "zlo_3" AS zlo_3,
    "zlo_5" AS zlo_5,
    "typ_rem_3" AS typ_rem_3,
    "volume" AS volume,
    "gen_auto" AS gen_auto,
    "num_ave" AS num_ave,
    "no_of" AS no_of,
    "no_lance" AS no_lance,
    "dat_mad" AS dat_mad,
    "qte_prep" AS qte_prep,
    "no_info" AS no_info,
    "no_serie" AS no_serie,
    "reg_deb" AS reg_deb,
    "no_contrat" AS no_contrat,
    "type_prix" AS type_prix,
    "hr_vp" AS hr_vp,
    "dat_vp" AS dat_vp,
    "qui_p" AS qui_p,
    "qte_epre" AS qte_epre,
    "no_bpr" AS no_bpr,
    "lien_emp" AS lien_emp,
    "cod_conv" AS cod_conv,
    "ndos" AS ndos,
    "s3_tar" AS s3_tar,
    "crit_cli_df" AS crit_cli_df,
    "typ_gra" AS typ_gra,
    "nb_uv" AS nb_uv,
    "qte_uc" AS qte_uc,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "poid_net" AS poid_net,
    "px_ttc" AS px_ttc,
    "s3_famille" AS s3_famille,
    "s4_famille" AS s4_famille,
    "qui_v" AS qui_v,
    "nom_pr2" AS nom_pr2,
    "no_mvtobois" AS no_mvtobois,
    "num_lot" AS num_lot,
    "num_colis" AS num_colis,
    "no_ctbois" AS no_ctbois,
    "no_lot" AS no_lot,
    "no_ligct" AS no_ligct,
    "no_tar_loc" AS no_tar_loc,
    "no_unique" AS no_unique,
    "mt_trsc" AS mt_trsc,
    "num_prix" AS num_prix,
    "MScod_fou" AS mscod_fou,
    "MScde_fou" AS mscde_fou,
    "MSlig_fou" AS mslig_fou,
    "poid_tot" AS poid_tot,
    "no_grp_c" AS no_grp_c,
    "cod_ppm" AS cod_ppm,
    "dat_ave" AS dat_ave,
    "no_ordre" AS no_ordre,
    "px_franco" AS px_franco,
    "px_std" AS px_std,
    "ach_ctr" AS ach_ctr,
    "px_ree" AS px_ree,
    "px_trs" AS px_trs,
    "cod_mo" AS cod_mo,
    "no_tarif" AS no_tarif,
    "uniq_id" AS uniq_id,
    "no_devis" AS no_devis,
    "nb_uv1" AS nb_uv1,
    "cod_op" AS cod_op,
    "no_u_perte" AS no_u_perte,
    "px_deb" AS px_deb,
    "qte_por" AS qte_por,
    "px_rvt_vte" AS px_rvt_vte,
    "mt_frais" AS mt_frais,
    "cod_fou_df" AS cod_fou_df,
    "cod_prolie" AS cod_prolie,
    "cod_rvt_ach" AS cod_rvt_ach,
    "cod_rvt_vte" AS cod_rvt_vte,
    "px_up" AS px_up,
    "qte_up" AS qte_up,
    "qte_ro" AS qte_ro,
    "marque" AS marque,
    "tare_p_2" AS tare_p_2,
    "cod_forfate" AS cod_forfate,
    "no_ord_bp" AS no_ord_bp,
    "no_deb" AS no_deb,
    "gen_con" AS gen_con,
    "cod_nom" AS cod_nom,
    "mt_titresto" AS mt_titresto,
    "_etl_valid_from" AS _etl_source_timestamp,
    "_etl_is_current" AS _etl_is_current,
    "_etl_run_id" AS _etl_run_id,
    CURRENT_TIMESTAMP AS _prep_loaded_at
    FROM {{ source('ods', 'lignecli') }}
    WHERE "_etl_is_current" = TRUE
    {% if is_incremental() %}
    AND "_etl_valid_from" > (
        SELECT COALESCE(MAX(_etl_source_timestamp), '1900-01-01'::timestamp)
        FROM {{ this }}
    )
    {% endif %}
    