{{ config(
    materialized='incremental',
    meta = {
        'dagster': {
            'group': 'prep',
            'domain': 'lignefou',
            'layer': 'prep'
        },
    },
    unique_key='uniq_id',
    incremental_strategy='merge',
    on_schema_change='sync_all_columns',
    post_hook=[
        "{% if is_incremental() %}DELETE FROM {{ this }} t WHERE NOT EXISTS (SELECT 1 FROM {{ source('ods', 'lignefou') }} s WHERE s.uniq_id = t.uniq_id AND s._etl_is_current = TRUE){% endif %}"
    ]
) }}

    /*
    ============================================================================
    PREP MODEL : lignefou
    ============================================================================
    Generated : 2025-12-30 15:27:27
    Source    : ods.lignefou
    Rows ODS  : 20,356
    Cols ODS  : 350
    Cols PREP : 172 (+ _prep_loaded_at)
    Strategy  : INCREMENTAL
    ============================================================================
    */

    SELECT
        "cod_fou" AS cod_fou,
    "typ_sai" AS typ_sai,
    "no_cde" AS no_cde,
    "no_ligne" AS no_ligne,
    "sous_type" AS sous_type,
    "typ_elem" AS typ_elem,
    "cod_pro" AS cod_pro,
    "nom_pro" AS nom_pro,
    "qte" AS qte,
    "px_ach" AS px_ach,
    "remise1" AS remise1,
    "rem_app" AS rem_app,
    "groupe" AS groupe,
    "famille" AS famille,
    "s_famille" AS s_famille,
    "fam_cpt" AS fam_cpt,
    "conv_px" AS conv_px,
    "refext" AS refext,
    "devise" AS devise,
    "uni_ach" AS uni_ach,
    "lib_unia" AS lib_unia,
    "lib_cona" AS lib_cona,
    "fam_tar" AS fam_tar,
    "code_tva" AS code_tva,
    "px_refa" AS px_refa,
    "pmp" AS pmp,
    "zal_1" AS zal_1,
    "znu_3" AS znu_3,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_2" AS zta_2,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zda_2" AS zda_2,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "depot" AS depot,
    "dat_liv" AS dat_liv,
    "forcer" AS forcer,
    "delai" AS delai,
    "refint" AS refint,
    "cod_cli" AS cod_cli,
    "conv_sto" AS conv_sto,
    "conv_md" AS conv_md,
    "conv_dec" AS conv_dec,
    "calc_uv" AS calc_uv,
    "qte_uc" AS qte_uc,
    "c_promo" AS c_promo,
    "sf_tar" AS sf_tar,
    "mt_ht" AS mt_ht,
    "cde_cli" AS cde_cli,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "typ_rem_1" AS typ_rem_1,
    "lien_nmc" AS lien_nmc,
    "edt_nmc" AS edt_nmc,
    "ord_nmc" AS ord_nmc,
    "zon_lib_1" AS zon_lib_1,
    "qte_ouv" AS qte_ouv,
    "qte_rec" AS qte_rec,
    "poids" AS poids,
    "dat_cde" AS dat_cde,
    "reliquat" AS reliquat,
    "reg_deb" AS reg_deb,
    "no_contrat" AS no_contrat,
    "type_prix" AS type_prix,
    "hr_liv" AS hr_liv,
    "no_of" AS no_of,
    "cod_conv" AS cod_conv,
    "ndos" AS ndos,
    "er_consm_1" AS er_consm_1,
    "er_consm_2" AS er_consm_2,
    "er_consm_3" AS er_consm_3,
    "er_consm_4" AS er_consm_4,
    "er_consm_5" AS er_consm_5,
    "er_consm_6" AS er_consm_6,
    "er_consm_7" AS er_consm_7,
    "er_consm_8" AS er_consm_8,
    "er_consm_9" AS er_consm_9,
    "er_consm_10" AS er_consm_10,
    "er_consm_11" AS er_consm_11,
    "er_consm_12" AS er_consm_12,
    "er_sr" AS er_sr,
    "es_sp" AS es_sp,
    "er_ep" AS er_ep,
    "er_sf" AS er_sf,
    "er_lib_1" AS er_lib_1,
    "er_lib_2" AS er_lib_2,
    "er_lib_4" AS er_lib_4,
    "er_lib_5" AS er_lib_5,
    "er_lib_6" AS er_lib_6,
    "s3_tar" AS s3_tar,
    "s4_tar" AS s4_tar,
    "er_icon_1" AS er_icon_1,
    "er_icon_2" AS er_icon_2,
    "er_icon_3" AS er_icon_3,
    "er_icon_4" AS er_icon_4,
    "er_icon_5" AS er_icon_5,
    "er_icon_6" AS er_icon_6,
    "er_icon_7" AS er_icon_7,
    "er_icon_8" AS er_icon_8,
    "er_icon_9" AS er_icon_9,
    "er_icon_10" AS er_icon_10,
    "er_icon_11" AS er_icon_11,
    "er_icon_12" AS er_icon_12,
    "er_tex_1" AS er_tex_1,
    "er_tex_2" AS er_tex_2,
    "er_couv" AS er_couv,
    "er_sems_1" AS er_sems_1,
    "er_sems_2" AS er_sems_2,
    "er_sems_3" AS er_sems_3,
    "er_sems_4" AS er_sems_4,
    "er_sems_5" AS er_sems_5,
    "er_sems_6" AS er_sems_6,
    "er_isem_1" AS er_isem_1,
    "er_isem_2" AS er_isem_2,
    "er_isem_3" AS er_isem_3,
    "er_isem_4" AS er_isem_4,
    "er_isem_5" AS er_isem_5,
    "er_isem_6" AS er_isem_6,
    "confirme" AS confirme,
    "no_info" AS no_info,
    "calcul" AS calcul,
    "nb_ua" AS nb_ua,
    "pp_ua" AS pp_ua,
    "poid_net" AS poid_net,
    "s3_famille" AS s3_famille,
    "s4_famille" AS s4_famille,
    "num_lot" AS num_lot,
    "num_colis" AS num_colis,
    "nom_pr2" AS nom_pr2,
    "no_ctbois" AS no_ctbois,
    "no_ligct" AS no_ligct,
    "cod_ori" AS cod_ori,
    "no_unique" AS no_unique,
    "er_cdfr" AS er_cdfr,
    "poid_tot" AS poid_tot,
    "no_grp_f" AS no_grp_f,
    "no_grp_tf" AS no_grp_tf,
    "volume" AS volume,
    "no_ordre" AS no_ordre,
    "num_ave" AS num_ave,
    "consigne" AS consigne,
    "dat_acc" AS dat_acc,
    "dat_livd" AS dat_livd,
    "maj_stk" AS maj_stk,
    "gen_csg" AS gen_csg,
    "qte_a_rec" AS qte_a_rec,
    "uniq_id" AS uniq_id,
    "nb_ua1" AS nb_ua1,
    "pays_ori" AS pays_ori,
    "px_rvt" AS px_rvt,
    "mt_frais" AS mt_frais,
    "cod_fou_df" AS cod_fou_df,
    "cod_prolie" AS cod_prolie,
    "cod_rvt_ach" AS cod_rvt_ach,
    "px_up" AS px_up,
    "qte_up" AS qte_up,
    "marque" AS marque,
    "tare_p_2" AS tare_p_2,
    "px_deb" AS px_deb,
    "gratuit" AS gratuit,
    "dat_enl" AS dat_enl,
    "cod_nom" AS cod_nom,
    "_etl_loaded_at" AS _etl_loaded_at,
    "_etl_run_id" AS _etl_run_id,
    "_etl_valid_from" AS _etl_source_timestamp,
    "_etl_is_current" AS _etl_is_current,
    CURRENT_TIMESTAMP AS _prep_loaded_at
    FROM {{ source('ods', 'lignefou') }}
    WHERE "_etl_is_current" = TRUE
    {% if is_incremental() %}
    AND "_etl_valid_from" > (
        SELECT COALESCE(MAX(_etl_source_timestamp), '1900-01-01'::timestamp)
        FROM {{ this }}
    )
    {% endif %}
    